/*
Research Administration Reporting Modernization
Snowflake-style reconciliation and reporting model
*/

CREATE OR REPLACE TEMP VIEW STG_LEGACY_PROPOSALS AS
SELECT
    PROPOSAL_NO::VARCHAR                                      AS LEGACY_PROPOSAL_ID,
    PI_ID::VARCHAR                                            AS LEGACY_INVESTIGATOR_ID,
    COLLEGE_TEXT::VARCHAR                                     AS LEGACY_COLLEGE_NAME,
    SPONSOR_NAME::VARCHAR                                     AS LEGACY_SPONSOR_NAME,
    PROPOSAL_TYPE_CD::VARCHAR                                 AS LEGACY_PROPOSAL_TYPE_CODE,
    TRY_TO_DATE(SUBMIT_DT::VARCHAR, 'YYYYMMDD')                AS SUBMISSION_DATE,
    TRY_TO_DECIMAL(REQUEST_AMT::VARCHAR, 18, 2)                AS REQUESTED_AMOUNT,
    PROP_STATUS_CD::VARCHAR                                   AS LEGACY_STATUS_CODE,
    NULLIF(AWARD_NO::VARCHAR, '')                             AS LEGACY_AWARD_ID,
    TRY_TO_DECIMAL(NULLIF(AWARD_AMT::VARCHAR, ''), 18, 2)     AS AWARDED_AMOUNT,
    TRY_TO_DATE(NULLIF(DECISION_DT::VARCHAR, ''), 'YYYYMMDD') AS DECISION_DATE,
    TRY_TO_DATE(NULLIF(AWARD_START_DT::VARCHAR, ''), 'YYYYMMDD') AS AWARD_START_DATE,
    TRY_TO_DATE(NULLIF(AWARD_END_DT::VARCHAR, ''), 'YYYYMMDD')   AS AWARD_END_DATE,
    TRY_TO_TIMESTAMP_NTZ(EXTRACT_TS::VARCHAR, 'YYYYMMDD HH24MISS') AS EXTRACT_TS
FROM RAW.LEGACY_PROPOSALS;

CREATE OR REPLACE TEMP VIEW STG_CURRENT_PROPOSALS AS
SELECT
    CURRENT_PROPOSAL_ID::VARCHAR                              AS CURRENT_PROPOSAL_ID,
    LEGACY_PROPOSAL_NO::VARCHAR                              AS LEGACY_PROPOSAL_ID,
    NULLIF(RESEARCHER_KEY::VARCHAR, '')                       AS INVESTIGATOR_ID,
    NULLIF(ORG_UNIT_CODE::VARCHAR, '')                        AS COLLEGE_CODE,
    NULLIF(SPONSOR_ID::VARCHAR, '')                           AS SPONSOR_ID,
    PROPOSAL_CATEGORY::VARCHAR                               AS PROPOSAL_TYPE,
    TO_DATE(TRY_TO_TIMESTAMP_TZ(SUBMITTED_AT::VARCHAR))       AS SUBMISSION_DATE,
    TRY_TO_DECIMAL(REQUESTED_TOTAL::VARCHAR, 18, 2)           AS REQUESTED_AMOUNT,
    WORKFLOW_STATUS::VARCHAR                                 AS CURRENT_STATUS_CODE,
    NULLIF(CURRENT_AWARD_ID::VARCHAR, '')                     AS AWARD_ID,
    TRY_TO_DECIMAL(NULLIF(OBLIGATED_AMOUNT::VARCHAR, ''), 18, 2) AS AWARDED_AMOUNT,
    TO_DATE(TRY_TO_TIMESTAMP_TZ(NULLIF(DECISION_AT::VARCHAR, ''))) AS DECISION_DATE,
    TRY_TO_DATE(NULLIF(AWARD_START_DATE::VARCHAR, ''))        AS AWARD_START_DATE,
    TRY_TO_DATE(NULLIF(AWARD_END_DATE::VARCHAR, ''))          AS AWARD_END_DATE,
    TRY_TO_TIMESTAMP_TZ(ROW_LAST_UPDATED::VARCHAR)            AS ROW_LAST_UPDATED
FROM RAW.CURRENT_PROPOSALS;

/* Keep one deterministic target record for field-level comparison, while
   preserving the full target table for duplicate detection. */
CREATE OR REPLACE TEMP VIEW STG_CURRENT_LATEST AS
SELECT *
FROM STG_CURRENT_PROPOSALS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY LEGACY_PROPOSAL_ID
    ORDER BY ROW_LAST_UPDATED DESC, CURRENT_PROPOSAL_ID DESC
) = 1;

/* 1. Control totals and migration completeness */
SELECT
    (SELECT COUNT(*) FROM STG_LEGACY_PROPOSALS) AS LEGACY_ROW_COUNT,
    (SELECT COUNT(*) FROM STG_CURRENT_PROPOSALS) AS CURRENT_ROW_COUNT,
    (SELECT COUNT(DISTINCT LEGACY_PROPOSAL_ID) FROM STG_CURRENT_PROPOSALS) AS MIGRATED_UNIQUE_COUNT,
    ROUND(
        (SELECT COUNT(DISTINCT LEGACY_PROPOSAL_ID) FROM STG_CURRENT_PROPOSALS)
        / NULLIF((SELECT COUNT(*) FROM STG_LEGACY_PROPOSALS), 0),
        4
    ) AS MIGRATION_COMPLETENESS;

/* 2. Missing source records */
SELECT L.LEGACY_PROPOSAL_ID
FROM STG_LEGACY_PROPOSALS L
LEFT JOIN STG_CURRENT_LATEST C USING (LEGACY_PROPOSAL_ID)
WHERE C.LEGACY_PROPOSAL_ID IS NULL;

/* 3. Duplicate target records */
SELECT LEGACY_PROPOSAL_ID, COUNT(*) AS TARGET_ROW_COUNT
FROM STG_CURRENT_PROPOSALS
GROUP BY LEGACY_PROPOSAL_ID
HAVING COUNT(*) > 1;

/* 4. Field-level reconciliation */
CREATE OR REPLACE TEMP VIEW QA_FIELD_RECONCILIATION AS
SELECT
    L.LEGACY_PROPOSAL_ID,
    C.CURRENT_PROPOSAL_ID,
    L.SUBMISSION_DATE AS LEGACY_SUBMISSION_DATE,
    C.SUBMISSION_DATE AS CURRENT_SUBMISSION_DATE,
    L.REQUESTED_AMOUNT AS LEGACY_REQUESTED_AMOUNT,
    C.REQUESTED_AMOUNT AS CURRENT_REQUESTED_AMOUNT,
    L.AWARDED_AMOUNT AS LEGACY_AWARDED_AMOUNT,
    C.AWARDED_AMOUNT AS CURRENT_AWARDED_AMOUNT,
    L.LEGACY_INVESTIGATOR_ID,
    C.INVESTIGATOR_ID,
    L.LEGACY_STATUS_CODE,
    C.CURRENT_STATUS_CODE,
    C.SPONSOR_ID,
    C.COLLEGE_CODE,
    I.INVESTIGATOR_ID AS VALID_INVESTIGATOR_ID,
    S.SPONSOR_ID AS VALID_SPONSOR_ID,
    O.COLLEGE_CODE AS VALID_COLLEGE_CODE,
    M.REPORTING_STATUS,
    IFF(L.SUBMISSION_DATE = C.SUBMISSION_DATE, 0, 1) AS SUBMISSION_DATE_MISMATCH,
    IFF(ABS(L.REQUESTED_AMOUNT - C.REQUESTED_AMOUNT) <= 0.01, 0, 1) AS REQUEST_AMOUNT_MISMATCH,
    IFF(ABS(COALESCE(L.AWARDED_AMOUNT, 0) - COALESCE(C.AWARDED_AMOUNT, 0)) <= 0.01, 0, 1) AS AWARD_AMOUNT_MISMATCH,
    IFF(C.INVESTIGATOR_ID IS NOT NULL AND I.INVESTIGATOR_ID IS NOT NULL, 0, 1) AS INVESTIGATOR_KEY_ISSUE,
    IFF(M.REPORTING_STATUS IS NOT NULL, 0, 1) AS STATUS_MAPPING_ISSUE,
    IFF(S.SPONSOR_ID IS NOT NULL, 0, 1) AS SPONSOR_KEY_ISSUE,
    IFF(O.COLLEGE_CODE IS NOT NULL, 0, 1) AS COLLEGE_KEY_ISSUE
FROM STG_LEGACY_PROPOSALS L
JOIN STG_CURRENT_LATEST C USING (LEGACY_PROPOSAL_ID)
LEFT JOIN RAW.DIM_INVESTIGATOR I ON C.INVESTIGATOR_ID = I.INVESTIGATOR_ID
LEFT JOIN RAW.DIM_SPONSOR S ON C.SPONSOR_ID = S.SPONSOR_ID
LEFT JOIN RAW.DIM_COLLEGE O ON C.COLLEGE_CODE = O.COLLEGE_CODE
LEFT JOIN RAW.STATUS_MAPPING M
  ON L.LEGACY_STATUS_CODE = M.LEGACY_STATUS_CODE
 AND C.CURRENT_STATUS_CODE = M.CURRENT_STATUS_CODE;

/* 5. Publishable issue view: one row per failed control */
CREATE OR REPLACE VIEW ANALYTICS.QA_MIGRATION_ISSUES AS
WITH MISSING AS (
    SELECT
        L.LEGACY_PROPOSAL_ID,
        NULL::VARCHAR AS CURRENT_PROPOSAL_ID,
        'MISSING_MIGRATION' AS ISSUE_TYPE,
        'Critical' AS SEVERITY,
        'record' AS FIELD_NAME
    FROM STG_LEGACY_PROPOSALS L
    LEFT JOIN STG_CURRENT_LATEST C USING (LEGACY_PROPOSAL_ID)
    WHERE C.LEGACY_PROPOSAL_ID IS NULL
),
DUPLICATES AS (
    SELECT
        LEGACY_PROPOSAL_ID,
        NULL::VARCHAR AS CURRENT_PROPOSAL_ID,
        'DUPLICATE_RECORD' AS ISSUE_TYPE,
        'High' AS SEVERITY,
        'record' AS FIELD_NAME
    FROM STG_CURRENT_PROPOSALS
    GROUP BY LEGACY_PROPOSAL_ID
    HAVING COUNT(*) > 1
),
FIELD_ISSUES AS (
    SELECT LEGACY_PROPOSAL_ID, CURRENT_PROPOSAL_ID, 'SUBMISSION_DATE_MISMATCH', 'Medium', 'submission_date'
    FROM QA_FIELD_RECONCILIATION WHERE SUBMISSION_DATE_MISMATCH = 1
    UNION ALL
    SELECT LEGACY_PROPOSAL_ID, CURRENT_PROPOSAL_ID, 'REQUEST_AMOUNT_MISMATCH', 'High', 'requested_amount'
    FROM QA_FIELD_RECONCILIATION WHERE REQUEST_AMOUNT_MISMATCH = 1
    UNION ALL
    SELECT LEGACY_PROPOSAL_ID, CURRENT_PROPOSAL_ID, 'AWARD_AMOUNT_MISMATCH', 'High', 'awarded_amount'
    FROM QA_FIELD_RECONCILIATION WHERE AWARD_AMOUNT_MISMATCH = 1
    UNION ALL
    SELECT LEGACY_PROPOSAL_ID, CURRENT_PROPOSAL_ID, 'MISSING_INVESTIGATOR', 'High', 'investigator_id'
    FROM QA_FIELD_RECONCILIATION WHERE INVESTIGATOR_KEY_ISSUE = 1
    UNION ALL
    SELECT LEGACY_PROPOSAL_ID, CURRENT_PROPOSAL_ID, 'UNMAPPED_STATUS', 'Medium', 'proposal_status'
    FROM QA_FIELD_RECONCILIATION WHERE STATUS_MAPPING_ISSUE = 1
    UNION ALL
    SELECT LEGACY_PROPOSAL_ID, CURRENT_PROPOSAL_ID, 'INVALID_SPONSOR', 'Medium', 'sponsor_id'
    FROM QA_FIELD_RECONCILIATION WHERE SPONSOR_KEY_ISSUE = 1
    UNION ALL
    SELECT LEGACY_PROPOSAL_ID, CURRENT_PROPOSAL_ID, 'INVALID_COLLEGE', 'Medium', 'college_code'
    FROM QA_FIELD_RECONCILIATION WHERE COLLEGE_KEY_ISSUE = 1
)
SELECT * FROM MISSING
UNION ALL SELECT * FROM DUPLICATES
UNION ALL SELECT * FROM FIELD_ISSUES;

/* 6. Reconciliation summary for the Data Quality dashboard */
SELECT
    ISSUE_TYPE,
    SEVERITY,
    COUNT(*) AS ISSUE_COUNT
FROM ANALYTICS.QA_MIGRATION_ISSUES
GROUP BY ISSUE_TYPE, SEVERITY
ORDER BY ISSUE_COUNT DESC, ISSUE_TYPE;

/* 7. Canonical reporting fact. Production logic should hold failed records out
   of certified reporting until they are remediated or explicitly approved. */
CREATE OR REPLACE VIEW ANALYTICS.FACT_RESEARCH_ACTIVITY AS
SELECT
    L.LEGACY_PROPOSAL_ID AS PROPOSAL_ID,
    C.INVESTIGATOR_ID,
    I.INVESTIGATOR_NAME,
    C.COLLEGE_CODE,
    O.COLLEGE_NAME,
    C.SPONSOR_ID,
    S.SPONSOR_NAME,
    S.SPONSOR_TYPE,
    C.PROPOSAL_TYPE,
    C.SUBMISSION_DATE,
    'FY' || RIGHT(YEAR(DATEADD(MONTH, 6, C.SUBMISSION_DATE))::VARCHAR, 2) AS FISCAL_YEAR,
    C.REQUESTED_AMOUNT,
    M.REPORTING_STATUS AS PROPOSAL_STATUS,
    C.AWARD_ID,
    C.AWARDED_AMOUNT,
    C.DECISION_DATE,
    DATEDIFF(DAY, C.SUBMISSION_DATE, C.DECISION_DATE) AS DAYS_TO_DECISION,
    C.AWARD_START_DATE,
    C.AWARD_END_DATE
FROM STG_LEGACY_PROPOSALS L
JOIN STG_CURRENT_LATEST C USING (LEGACY_PROPOSAL_ID)
JOIN RAW.DIM_INVESTIGATOR I ON C.INVESTIGATOR_ID = I.INVESTIGATOR_ID
JOIN RAW.DIM_SPONSOR S ON C.SPONSOR_ID = S.SPONSOR_ID
JOIN RAW.DIM_COLLEGE O ON C.COLLEGE_CODE = O.COLLEGE_CODE
JOIN RAW.STATUS_MAPPING M
  ON L.LEGACY_STATUS_CODE = M.LEGACY_STATUS_CODE
 AND C.CURRENT_STATUS_CODE = M.CURRENT_STATUS_CODE
WHERE NOT EXISTS (
    SELECT 1
    FROM ANALYTICS.QA_MIGRATION_ISSUES Q
    WHERE Q.LEGACY_PROPOSAL_ID = L.LEGACY_PROPOSAL_ID
);

